name: myanmar_calendar_dart_cli
description: Myanmar calendar Dart CLI package
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  # Myanmar Calendar Support
  myanmar_calendar_dart: ^1.0.0
  pub_updater: ^0.5.0


dev_dependencies:
  build_runner: ^2.8.0
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0

executables:
  mycal:
